
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import javax.swing.JOptionPane;

/**
 *
 * @author Elena Koevska
 */
public class ChangePassPanel extends javax.swing.JPanel implements PropertyChangeListener {

    /**
     * Reference to the main frame.
     */
    private ClientFrame mainFrame;
    
    /**
     * Username of currently logged-in user.
     */
    private String username;
    
    /**
     * PIN of currently logged-in user.
     */
    private String egn;
    
    /**
     * Creates new form ChangePassPanel
     */
    public ChangePassPanel() {
        initComponents();
    }

    /**
     * Used to update component's private fields when the main frame fires a property
     * change event.
     *
     * @param pce event's instance
     */
    @Override
    public void propertyChange(PropertyChangeEvent pce) {
        if (pce.getPropertyName().equals("currentUser")) {
            // Set the reference to the main frame.
            mainFrame = (ClientFrame) pce.getSource();

            // Set username.
            username = ((User) pce.getNewValue()).getUsername();
            
            // Set PIN.
            egn = ((User) pce.getNewValue()).getEgn();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblOldPass = new javax.swing.JLabel();
        lblNewPass = new javax.swing.JLabel();
        lblNewPassConfirm = new javax.swing.JLabel();
        pfieldNewPass = new javax.swing.JPasswordField();
        pfieldOldPass = new javax.swing.JPasswordField();
        pfieldNewPassConfirm = new javax.swing.JPasswordField();
        btnSavePass = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Смяна на парола", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 16), new java.awt.Color(120, 169, 203))); // NOI18N
        setMaximumSize(new java.awt.Dimension(804, 688));
        setMinimumSize(new java.awt.Dimension(804, 688));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(804, 688));

        lblOldPass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblOldPass.setText("Стара парола");

        lblNewPass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNewPass.setText("Нова парола");

        lblNewPassConfirm.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNewPassConfirm.setText("Потвърди нова парола");

        pfieldNewPass.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        pfieldNewPass.setMaximumSize(new java.awt.Dimension(140, 25));
        pfieldNewPass.setMinimumSize(new java.awt.Dimension(140, 25));
        pfieldNewPass.setPreferredSize(new java.awt.Dimension(140, 24));

        pfieldOldPass.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        pfieldOldPass.setMaximumSize(new java.awt.Dimension(140, 25));
        pfieldOldPass.setMinimumSize(new java.awt.Dimension(140, 25));
        pfieldOldPass.setPreferredSize(new java.awt.Dimension(140, 24));

        pfieldNewPassConfirm.setMaximumSize(new java.awt.Dimension(140, 24));
        pfieldNewPassConfirm.setMinimumSize(new java.awt.Dimension(140, 24));
        pfieldNewPassConfirm.setPreferredSize(new java.awt.Dimension(140, 24));

        btnSavePass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSavePass.setText("Промени");
        btnSavePass.setMaximumSize(new java.awt.Dimension(140, 32));
        btnSavePass.setMinimumSize(new java.awt.Dimension(140, 32));
        btnSavePass.setPreferredSize(new java.awt.Dimension(140, 32));
        btnSavePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSavePassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblOldPass)
                    .addComponent(lblNewPass)
                    .addComponent(lblNewPassConfirm))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(pfieldNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pfieldOldPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSavePass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pfieldNewPassConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(446, 446, 446))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblOldPass)
                    .addComponent(pfieldOldPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblNewPass)
                    .addComponent(pfieldNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblNewPassConfirm)
                    .addComponent(pfieldNewPassConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(btnSavePass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(486, 486, 486))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSavePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSavePassActionPerformed
        // Check if old password field is empty.
        if (pfieldOldPass.getPassword().length == 0) {
            JOptionPane.showMessageDialog(mainFrame, "Полето 'Стара парола' не може да бъде празно!", "Грешка", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Check if old password is valid.
        User request = new User();
        request.setRequest("login");
        request.setUsername(username);
        request.setEgn(egn);
        request.setPassword(String.valueOf(pfieldOldPass.getPassword()));
        User response = (User) mainFrame.getClient().runClient(request);
        if (!response.getLoggedIn()) {
            JOptionPane.showMessageDialog(mainFrame, "Моля, въведете валидна текуща парола!", "Грешка", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Ensure new pass and confirm new pass are not empty.
        if (pfieldNewPass.getPassword().length == 0 || pfieldNewPassConfirm.getPassword().length == 0) {
            JOptionPane.showMessageDialog(mainFrame, "Полетата 'Нова парола' и 'Потвърди нова парола' не трябва да са празни!", "Грешка", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Ensure new pass and confirm new pass match.
        if (!String.valueOf(pfieldNewPass.getPassword()).equals(String.valueOf(pfieldNewPassConfirm.getPassword()))) {
            JOptionPane.showMessageDialog(mainFrame, "Данните в полетата 'Нова парола' и 'Потвърди нова парола' трябва да съвпадат!", "Грешка", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // TODO: Password requirments (e.g. mininum length etc.)?
        // At last, we are ready to go!
        request.setRequest("updatePass");
        request.setUsername(username);
        request.setEgn(egn);
        request.setPassword(String.valueOf(pfieldNewPass.getPassword()));
        response = (User) mainFrame.getClient().runClient(request);
        if (response.getResponse() == null) {
            JOptionPane.showMessageDialog(mainFrame, "Промяната на паролата беше успешна.", "Съобщение", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(mainFrame, "Грешка при опит за промяна на парола: " + response.getResponse(), "Грешка", JOptionPane.ERROR_MESSAGE);
        }

        // Clear field values.
        pfieldOldPass.setText(null);
        pfieldNewPass.setText(null);
        pfieldNewPassConfirm.setText(null);
    }//GEN-LAST:event_btnSavePassActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSavePass;
    private javax.swing.JLabel lblNewPass;
    private javax.swing.JLabel lblNewPassConfirm;
    private javax.swing.JLabel lblOldPass;
    private javax.swing.JPasswordField pfieldNewPass;
    private javax.swing.JPasswordField pfieldNewPassConfirm;
    private javax.swing.JPasswordField pfieldOldPass;
    // End of variables declaration//GEN-END:variables
}
