
import java.awt.CardLayout;
import java.awt.event.KeyEvent;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;

/**
 *
 * @author Elena Koevska & Julia Protich
 */
public class ClientFrame extends javax.swing.JFrame {

    /**
     * Creates new form ClientFrame
     *
     * @param user - Current user instance.
     * @param currency - Current currency instance.
     * @param client - Current SSL client instance.
     */
    public ClientFrame(User user, Currency currency, SSLClient client) {
        // Set background image.
        try {
            this.setContentPane(new BackgroundImage(ImageIO.read(new File("client_frame_bg.jpg"))));
        } catch (java.io.IOException e) {
            System.out.println(e.getMessage());
        }

        // Init components.
        initComponents();

        // Add all required components as listeners of the ClientFrame.
        addPropertyChangeListener(transactionsPanel);
        addPropertyChangeListener(currencyPanel);
        addPropertyChangeListener(userProfilePanel);
        addPropertyChangeListener(accountBalancePanel);
        addPropertyChangeListener(transactionsInfoPanel);

        // Fire property change events so the listeners can update their UI state.
        firePropertyChange("currentUser", currentUser, user);
        firePropertyChange("currencyData", currencyData, currency);

        // Init private fields from the constructor params.
        this.currentUser = user;
        this.currencyData = currency;
        this.client = client;
    }
    
    public User getCurrentUser() {
        return currentUser;
    }
    
    public SSLClient getClient() {
        return client;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        accountBalancePanel = new AccountBalancePanel();
        transactionsInfoPanel = new TransactionsInfoPanel();
        pnlChangePass = new javax.swing.JPanel();
        lblOldPass = new javax.swing.JLabel();
        lblNewPass = new javax.swing.JLabel();
        lblNewPassConfirm = new javax.swing.JLabel();
        btnSavePass = new javax.swing.JButton();
        pfieldOldPass = new javax.swing.JPasswordField();
        pfieldNewPass = new javax.swing.JPasswordField();
        pfieldNewPassConfirm = new javax.swing.JPasswordField();
        userProfilePanel = new UserProfilePanel();
        transactionsPanel = new TransactionsPanel();
        MenuPanel = new javax.swing.JPanel();
        btnAccBallance = new javax.swing.JButton();
        btnPayments = new javax.swing.JButton();
        btnChangePass = new javax.swing.JButton();
        btnUserProfile = new javax.swing.JButton();
        btnTransactions = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        currencyPanel = new CurrencyPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ELU_Bank");
        setIconImages(null);
        setMaximumSize(new java.awt.Dimension(1024, 720));
        setMinimumSize(new java.awt.Dimension(1024, 720));
        setPreferredSize(new java.awt.Dimension(1024, 720));
        setResizable(false);

        MainPanel.setBackground(new java.awt.Color(102, 255, 255));
        MainPanel.setMaximumSize(new java.awt.Dimension(804, 688));
        MainPanel.setMinimumSize(new java.awt.Dimension(804, 688));
        MainPanel.setOpaque(false);
        MainPanel.setPreferredSize(new java.awt.Dimension(804, 688));
        MainPanel.setLayout(new java.awt.CardLayout());
        MainPanel.add(accountBalancePanel, "card2");
        MainPanel.add(transactionsInfoPanel, "card3");

        pnlChangePass.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Смяна на парола", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(96, 151, 205))); // NOI18N
        pnlChangePass.setMaximumSize(new java.awt.Dimension(804, 680));
        pnlChangePass.setMinimumSize(new java.awt.Dimension(804, 680));
        pnlChangePass.setOpaque(false);
        pnlChangePass.setPreferredSize(new java.awt.Dimension(804, 680));

        lblOldPass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblOldPass.setText("Стара парола");

        lblNewPass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNewPass.setText("Нова парола");

        lblNewPassConfirm.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNewPassConfirm.setText("Потвърди нова парола");

        btnSavePass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSavePass.setText("Промени");
        btnSavePass.setMaximumSize(new java.awt.Dimension(140, 32));
        btnSavePass.setMinimumSize(new java.awt.Dimension(140, 32));
        btnSavePass.setPreferredSize(new java.awt.Dimension(140, 32));
        btnSavePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSavePassActionPerformed(evt);
            }
        });

        pfieldOldPass.setMaximumSize(new java.awt.Dimension(140, 24));
        pfieldOldPass.setMinimumSize(new java.awt.Dimension(140, 24));
        pfieldOldPass.setPreferredSize(new java.awt.Dimension(140, 24));

        pfieldNewPass.setMaximumSize(new java.awt.Dimension(140, 24));
        pfieldNewPass.setMinimumSize(new java.awt.Dimension(140, 24));
        pfieldNewPass.setPreferredSize(new java.awt.Dimension(140, 24));

        pfieldNewPassConfirm.setMaximumSize(new java.awt.Dimension(140, 24));
        pfieldNewPassConfirm.setMinimumSize(new java.awt.Dimension(140, 24));
        pfieldNewPassConfirm.setPreferredSize(new java.awt.Dimension(140, 24));

        javax.swing.GroupLayout pnlChangePassLayout = new javax.swing.GroupLayout(pnlChangePass);
        pnlChangePass.setLayout(pnlChangePassLayout);
        pnlChangePassLayout.setHorizontalGroup(
            pnlChangePassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChangePassLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(pnlChangePassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblOldPass)
                    .addComponent(lblNewPass)
                    .addComponent(lblNewPassConfirm))
                .addGap(18, 18, 18)
                .addGroup(pnlChangePassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(pfieldNewPassConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pfieldNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pfieldOldPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSavePass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(434, Short.MAX_VALUE))
        );
        pnlChangePassLayout.setVerticalGroup(
            pnlChangePassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChangePassLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(pnlChangePassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOldPass)
                    .addComponent(pfieldOldPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(pnlChangePassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNewPass)
                    .addComponent(pfieldNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(pnlChangePassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNewPassConfirm)
                    .addComponent(pfieldNewPassConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(btnSavePass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(486, Short.MAX_VALUE))
        );

        MainPanel.add(pnlChangePass, "card4");
        MainPanel.add(userProfilePanel, "card5");
        MainPanel.add(transactionsPanel, "card6");

        MenuPanel.setBackground(java.awt.SystemColor.window);
        MenuPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Меню", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Verdana", 0, 18), new java.awt.Color(105, 169, 212))); // NOI18N
        MenuPanel.setForeground(new java.awt.Color(255, 255, 255));
        MenuPanel.setDoubleBuffered(false);
        MenuPanel.setMaximumSize(new java.awt.Dimension(186, 680));
        MenuPanel.setMinimumSize(new java.awt.Dimension(186, 680));
        MenuPanel.setOpaque(false);
        MenuPanel.setPreferredSize(new java.awt.Dimension(200, 680));
        MenuPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAccBallance.setBackground(new java.awt.Color(235, 230, 230));
        btnAccBallance.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnAccBallance.setText("Наличност по сметки");
        btnAccBallance.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAccBallance.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnAccBallance.setMargin(new java.awt.Insets(2, 4, 2, 4));
        btnAccBallance.setMaximumSize(new java.awt.Dimension(180, 33));
        btnAccBallance.setMinimumSize(new java.awt.Dimension(180, 33));
        btnAccBallance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccBallanceActionPerformed(evt);
            }
        });
        btnAccBallance.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnAccBallanceKeyPressed(evt);
            }
        });
        MenuPanel.add(btnAccBallance, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 36, 180, 32));

        btnPayments.setBackground(new java.awt.Color(235, 230, 230));
        btnPayments.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnPayments.setText("Движение по сметки");
        btnPayments.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPayments.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnPayments.setMargin(new java.awt.Insets(2, 4, 2, 4));
        btnPayments.setMaximumSize(new java.awt.Dimension(180, 33));
        btnPayments.setMinimumSize(new java.awt.Dimension(180, 33));
        btnPayments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaymentsActionPerformed(evt);
            }
        });
        btnPayments.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnPaymentsKeyPressed(evt);
            }
        });
        MenuPanel.add(btnPayments, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 74, 180, 32));

        btnChangePass.setBackground(new java.awt.Color(235, 230, 230));
        btnChangePass.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnChangePass.setText("Смяна на парола");
        btnChangePass.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnChangePass.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnChangePass.setMargin(new java.awt.Insets(2, 4, 2, 4));
        btnChangePass.setMaximumSize(new java.awt.Dimension(180, 33));
        btnChangePass.setMinimumSize(new java.awt.Dimension(180, 33));
        btnChangePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePassActionPerformed(evt);
            }
        });
        btnChangePass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnChangePassKeyPressed(evt);
            }
        });
        MenuPanel.add(btnChangePass, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 112, 180, 32));

        btnUserProfile.setBackground(new java.awt.Color(235, 230, 230));
        btnUserProfile.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnUserProfile.setText("Моят профил");
        btnUserProfile.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnUserProfile.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnUserProfile.setMargin(new java.awt.Insets(2, 4, 2, 4));
        btnUserProfile.setMaximumSize(new java.awt.Dimension(180, 33));
        btnUserProfile.setMinimumSize(new java.awt.Dimension(180, 33));
        btnUserProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserProfileActionPerformed(evt);
            }
        });
        btnUserProfile.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnUserProfileKeyPressed(evt);
            }
        });
        MenuPanel.add(btnUserProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 150, 180, 32));

        btnTransactions.setBackground(new java.awt.Color(255, 255, 255));
        btnTransactions.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnTransactions.setText("Преводи");
        btnTransactions.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnTransactions.setInheritsPopupMenu(true);
        btnTransactions.setMargin(new java.awt.Insets(2, 4, 2, 4));
        btnTransactions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransactionsActionPerformed(evt);
            }
        });
        btnTransactions.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnTransactionsKeyPressed(evt);
            }
        });
        MenuPanel.add(btnTransactions, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 188, 180, 32));

        btnLogout.setBackground(new java.awt.Color(235, 230, 230));
        btnLogout.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnLogout.setText("Изход (Logout)");
        btnLogout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLogout.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnLogout.setMargin(new java.awt.Insets(2, 4, 2, 4));
        btnLogout.setMaximumSize(new java.awt.Dimension(180, 33));
        btnLogout.setMinimumSize(new java.awt.Dimension(180, 33));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        btnLogout.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnLogoutKeyPressed(evt);
            }
        });
        MenuPanel.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 620, 180, 32));
        MenuPanel.add(currencyPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 500, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(MenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(MenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSavePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSavePassActionPerformed
        // Check if old password field is empty.
        if (pfieldOldPass.getPassword().length == 0) {
            JOptionPane.showMessageDialog(this, "Полето 'Стара парола' не може да бъде празно!", "Грешка", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Check if old password is valid.
        User request = new User();
        request.setRequest("login");
        request.setUsername(currentUser.getUsername());
        request.setPassword(String.valueOf(pfieldOldPass.getPassword()));
        User response = (User) client.runClient(request);
        if (!response.getLoggedIn()) {
            JOptionPane.showMessageDialog(this, "Моля, въведете валидна текуща парола!", "Грешка", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Ensure new pass and confirm new pass are not empty.
        if (pfieldNewPass.getPassword().length == 0 || pfieldNewPassConfirm.getPassword().length == 0) {
            JOptionPane.showMessageDialog(this, "Полетата 'Нова парола' и 'Потвърди нова парола' не трябва да са празни!", "Грешка", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Ensure new pass and confirm new pass match.
        if (!String.valueOf(pfieldNewPass.getPassword()).equals(String.valueOf(pfieldNewPassConfirm.getPassword()))) {
            JOptionPane.showMessageDialog(this, "Данните в полетата 'Нова парола' и 'Потвърди нова парола' трябва да съвпадат!", "Грешка", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // TODO: Password requirments (e.g. mininum length etc.)?
        // At last, we are ready to go!
        request.setRequest("updatePass");
        request.setUsername(currentUser.getUsername());
        request.setPassword(String.valueOf(pfieldNewPass.getPassword()));
        response = (User) client.runClient(request);
        if (response.getResponse() == null) {
            JOptionPane.showMessageDialog(this, "Промяната на паролата беше успешна.", "Съобщение", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Грешка при опит за промяна на парола: " + response.getResponse(), "Грешка", JOptionPane.ERROR_MESSAGE);
        }

        // Clear field values.
        pfieldOldPass.setText(null);
        pfieldNewPass.setText(null);
        pfieldNewPassConfirm.setText(null);
    }//GEN-LAST:event_btnSavePassActionPerformed

    private void btnTransactionsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnTransactionsKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            btnLogout.doClick();
        } else if (evt.getKeyCode() == KeyEvent.VK_UP) {
            btnUserProfile.doClick();
            btnUserProfile.grabFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            btnLogout.grabFocus();
        }
    }//GEN-LAST:event_btnTransactionsKeyPressed

    private void btnTransactionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransactionsActionPerformed
        changePanel("card6");
    }//GEN-LAST:event_btnTransactionsActionPerformed

    private void btnLogoutKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnLogoutKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE
                || evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnLogout.doClick();
        } else if (evt.getKeyCode() == KeyEvent.VK_UP) {
            btnTransactions.doClick();
            btnTransactions.grabFocus();
        }
    }//GEN-LAST:event_btnLogoutKeyPressed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
        dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnUserProfileKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnUserProfileKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            btnLogout.doClick();
        } else if (evt.getKeyCode() == KeyEvent.VK_UP) {
            btnChangePass.doClick();
            btnChangePass.grabFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            btnTransactions.doClick();
            btnTransactions.grabFocus();
        }
    }//GEN-LAST:event_btnUserProfileKeyPressed

    private void btnUserProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserProfileActionPerformed
        changePanel("card5");
    }//GEN-LAST:event_btnUserProfileActionPerformed

    private void btnChangePassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnChangePassKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            btnLogout.doClick();
        } else if (evt.getKeyCode() == KeyEvent.VK_UP) {
            btnPayments.doClick();
            btnPayments.grabFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            btnUserProfile.doClick();
            btnUserProfile.grabFocus();
        }
    }//GEN-LAST:event_btnChangePassKeyPressed

    private void btnChangePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePassActionPerformed
        changePanel("card4");
    }//GEN-LAST:event_btnChangePassActionPerformed

    private void btnPaymentsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnPaymentsKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            btnLogout.doClick();
        } else if (evt.getKeyCode() == KeyEvent.VK_UP) {
            btnAccBallance.doClick();
            btnAccBallance.grabFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            btnChangePass.doClick();
            btnChangePass.grabFocus();
        }
    }//GEN-LAST:event_btnPaymentsKeyPressed

    private void btnPaymentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaymentsActionPerformed
        changePanel("card3");
    }//GEN-LAST:event_btnPaymentsActionPerformed

    private void btnAccBallanceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnAccBallanceKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            btnLogout.doClick();
        } else if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            btnPayments.doClick();
            btnPayments.grabFocus();
        }
    }//GEN-LAST:event_btnAccBallanceKeyPressed

    private void btnAccBallanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccBallanceActionPerformed
        changePanel("card2");
    }//GEN-LAST:event_btnAccBallanceActionPerformed

    /**
     * Shows the given panel in the main panel.
     *
     * @param panelName - Panel name as set in CardName property.
     */
    private void changePanel(String panelName) {
        CardLayout mainPanelLayout = (CardLayout) (MainPanel.getLayout());
        mainPanelLayout.show(MainPanel, panelName);
    }
    
    private User currentUser;
    private Currency currencyData;
    private SSLClient client;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel MenuPanel;
    private AccountBalancePanel accountBalancePanel;
    private javax.swing.JButton btnAccBallance;
    private javax.swing.JButton btnChangePass;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPayments;
    private javax.swing.JButton btnSavePass;
    private javax.swing.JButton btnTransactions;
    private javax.swing.JButton btnUserProfile;
    private CurrencyPanel currencyPanel;
    private javax.swing.JLabel lblNewPass;
    private javax.swing.JLabel lblNewPassConfirm;
    private javax.swing.JLabel lblOldPass;
    private javax.swing.JPasswordField pfieldNewPass;
    private javax.swing.JPasswordField pfieldNewPassConfirm;
    private javax.swing.JPasswordField pfieldOldPass;
    private javax.swing.JPanel pnlChangePass;
    private TransactionsInfoPanel transactionsInfoPanel;
    private TransactionsPanel transactionsPanel;
    private UserProfilePanel userProfilePanel;
    // End of variables declaration//GEN-END:variables
}
