/**
 *
 * @author USER
 */
import java.awt.Font;
import javax.swing.table.DefaultTableModel;

public class InterestsForm extends javax.swing.JFrame {

    /**
     * Creates new form InterestsForm
     */
    DefaultTableModel model;

    public InterestsForm() {
        initComponents();

        model = (DefaultTableModel) jTable1.getModel();
        model.setColumnIdentifiers(new Object[]{
            "Нива на олихвяване, според остатъка ", "Годишен лихвен процент BGN  ", "Годишен лихвен процент EUR ", "Годишен лихвен процент USD "});

        model.insertRow(0, new Object[]{"до 99,99", "0,35%", "0,35%", "0,35%"});
        model.insertRow(1, new Object[]{"от 100,00 до 999,99", "1,00%", "0,60%", "0,50%"});
        model.insertRow(2, new Object[]{"от 1 000,00 до 4 999,99", "1,75%", "1,00%", "0,75%"});
        model.insertRow(3, new Object[]{"от 5 000,00 до 9 999,99", "2,75%", "1,20%", "0,95%"});
        model.insertRow(4, new Object[]{"над 10 000,00", " 3,50%", " 2,00%", "1,50%"});

        for (int count = 0; count < 5; count++) {
            jTable1.setRowHeight(count, 70);
            jTable1.setFont(new Font("Times New Roman", Font.ITALIC, 18));
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnBackHomePage = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        backgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1040, 700));
        setMinimumSize(new java.awt.Dimension(1040, 700));
        setPreferredSize(new java.awt.Dimension(1040, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.lightGray));
        jPanel1.setOpaque(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 976, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 980, 370));

        btnBackHomePage.setBackground(new java.awt.Color(168, 199, 200));
        btnBackHomePage.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        btnBackHomePage.setText("Back to home page");
        btnBackHomePage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackHomePageActionPerformed(evt);
            }
        });
        getContentPane().add(btnBackHomePage, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 550, 140, 40));

        btnExit.setBackground(new java.awt.Color(168, 199, 200));
        btnExit.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 550, 130, 40));

        backgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/abstract_background.jpg"))); // NOI18N
        backgroundLabel.setPreferredSize(new java.awt.Dimension(1024, 720));
        getContentPane().add(backgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackHomePageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackHomePageActionPerformed
        dispose();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new LoginFrame().setVisible(true);
                new InterestsForm().setVisible(false);
            }
        });
    }//GEN-LAST:event_btnBackHomePageActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JButton btnBackHomePage;
    private javax.swing.JButton btnExit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
