
/**
 * Class used to show information about Internet Banking 
 * 
 * @author Lyubomira Kazandzhieva
 */
public class OnlineBankingInfo extends javax.swing.JFrame {

    /**
     * Creates new form OnlineBankingInfo
     */
    public OnlineBankingInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaOnlineBankingInfo = new javax.swing.JTextArea();
        lblbackgr = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1050, 680));
        setMinimumSize(new java.awt.Dimension(1050, 680));
        setPreferredSize(new java.awt.Dimension(1000, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setOpaque(false);

        txtAreaOnlineBankingInfo.setEditable(false);
        txtAreaOnlineBankingInfo.setColumns(20);
        txtAreaOnlineBankingInfo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtAreaOnlineBankingInfo.setRows(5);
        txtAreaOnlineBankingInfo.setText("Какво представлява?\n\nДа проверите в реално време:\n•\tНаличността, плащанията и постъпленията по Вашите сметки (разплащателни, спестовни, депозитни); \n•\tНаличностите по разплащателните сметки в ELUBank са в реално време; \n•\tОперациите извършени с Ваши банкови карти и статус на картите; \n•\tИнформация за Вашите кредити (остатък, вноска, падежна дата и т.н.); \n•\tРазмерът на начислената до момента лихва по Вашите спестовни сметки и депозити, падежни дати и др.; \n\nДа наредите преводи:\n•\tМежду Ваши сметки в Банката – в лева и валута. \n•\tПреводите по сметки в банката (Ваши или към трети лица) се извършват в реално време. \n\nДа спестявате:\n•\tЧрез спестовна компонента Банка ELUBank Ви предоставя възможност да спестявате, като парите остават винаги на Ваше разположение, без ограничения за падежна дата, минимални суми, брой тегления, без допълнителни такси. \n•\tЧрез Виртуалния срочен депозит получавате атрактивни лихвени нива;\n\nКолко ще ми струва?\n•\tДостъпът до портала за електронно банкиране е безплатен \n");
        txtAreaOnlineBankingInfo.setOpaque(false);
        txtAreaOnlineBankingInfo.setPreferredSize(new java.awt.Dimension(1200, 276));
        jScrollPane1.setViewportView(txtAreaOnlineBankingInfo);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 980, 400));

        lblbackgr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/abstract_background.jpg"))); // NOI18N
        getContentPane().add(lblbackgr, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblbackgr;
    private javax.swing.JTextArea txtAreaOnlineBankingInfo;
    // End of variables declaration//GEN-END:variables
}
