/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author USER
 */
public class OnlineBankingInfo extends javax.swing.JFrame {

    /**
     * Creates new form OnlineBankingInfo
     */
    public OnlineBankingInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaOnlineBankingInfo = new javax.swing.JTextArea();
        lblbackgr = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1050, 680));
        setMinimumSize(new java.awt.Dimension(1050, 680));
        setPreferredSize(new java.awt.Dimension(1040, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setOpaque(false);

        txtAreaOnlineBankingInfo.setColumns(20);
        txtAreaOnlineBankingInfo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtAreaOnlineBankingInfo.setRows(5);
        txtAreaOnlineBankingInfo.setText("Какво представлява?\nДа проверите в реално време:\n•\tНаличността, плащанията и постъпленията по Вашите сметки (разплащателни, спестовни, депозитни); \n•\tНаличностите по разплащателните сметки в ELUBank са в реално време; \n•\tОперациите извършени с Ваши банкови карти и статус на картите; \n•\tИнформация за Вашите кредити (остатък, вноска, падежна дата и т.н.); \n•\tРазмерът на начислената до момента лихва по Вашите спестовни сметки и депозити, падежни дати и др.; \nДа наредите преводи:\n•\tМежду Ваши сметки в Банката – в лева и валута. \n•\tПреводите по сметки в банката (Ваши или към трети лица) се извършват в реално време. \nДа спестявате:\n•\tЧрез спестовна компонента Банка ELUBank Ви предоставя възможност да спестявате, като парите остават винаги на Ваше разположение, без ограничения за падежна дата, минимални суми, брой тегления, без допълнителни такси. \n•\tЧрез Виртуалния срочен депозит получавате атрактивни лихвени нива \nКолко ще ми струва?\n•\tДостъпът до портала за електронно банкиране е безплатен \n");
        txtAreaOnlineBankingInfo.setOpaque(false);
        jScrollPane1.setViewportView(txtAreaOnlineBankingInfo);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 980, 400));

        lblbackgr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/abstract_background.jpg"))); // NOI18N
        getContentPane().add(lblbackgr, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OnlineBankingInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OnlineBankingInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OnlineBankingInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OnlineBankingInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OnlineBankingInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblbackgr;
    private javax.swing.JTextArea txtAreaOnlineBankingInfo;
    // End of variables declaration//GEN-END:variables
}
