
import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author USER
 */
public class RegistrationForm extends javax.swing.JFrame {

    /**
     * Creates new form SetNewClient
     */
    public RegistrationForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ELUBank_lbl = new javax.swing.JLabel();
        MenuCardLayoutPanel = new javax.swing.JPanel();
        ManagementPanel = new javax.swing.JPanel();
        CreateNewClientButton = new javax.swing.JButton();
        CreateNewAccountButton = new javax.swing.JButton();
        DeleteBankingAccount = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        CentralCardLayoutPanel = new javax.swing.JPanel();
        WelcomePanel = new javax.swing.JPanel();
        Welcome_lbl = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        RegistrationPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Nme_registr = new javax.swing.JTextField();
        secondName_resitr = new javax.swing.JTextField();
        surNme_registr = new javax.swing.JTextField();
        PIN_registr = new javax.swing.JTextField();
        address_registr = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        comboBoxCountry = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        city_registr = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        phone_restr = new javax.swing.JTextField();
        mail_registr = new javax.swing.JTextField();
        ConfirmButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        userName_txt = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        CancelButton = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        comboBoxDateOfBirth = new javax.swing.JComboBox();
        comboBoxMonthOfBirth = new javax.swing.JComboBox();
        comboBoxYearOfBirth = new javax.swing.JComboBox();
        comboBoxUserType = new javax.swing.JComboBox();
        NewAccountPanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        fnme_txt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        mname_txt = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        lname_txt = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        egn_txt = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        user_txt = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        access_txt = new javax.swing.JTextField();
        search_button = new javax.swing.JButton();
        PartBackground_lbl = new javax.swing.JLabel();
        DeleteAccountPanel = new javax.swing.JPanel();
        BackgroundPart_lbl = new javax.swing.JLabel();
        BackgroundLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1040, 700));
        setMinimumSize(new java.awt.Dimension(1040, 700));
        setPreferredSize(new java.awt.Dimension(1040, 700));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ELUBank_lbl.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        ELUBank_lbl.setForeground(new java.awt.Color(0, 153, 153));
        ELUBank_lbl.setText("ELU Bank");
        getContentPane().add(ELUBank_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 550, -1, -1));

        MenuCardLayoutPanel.setMaximumSize(new java.awt.Dimension(170, 430));
        MenuCardLayoutPanel.setMinimumSize(new java.awt.Dimension(170, 430));
        MenuCardLayoutPanel.setOpaque(false);
        MenuCardLayoutPanel.setPreferredSize(new java.awt.Dimension(200, 430));
        MenuCardLayoutPanel.setLayout(new java.awt.CardLayout());

        ManagementPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Management Panel", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 2, 18), new java.awt.Color(0, 153, 153))); // NOI18N
        ManagementPanel.setOpaque(false);
        ManagementPanel.setPreferredSize(new java.awt.Dimension(200, 430));

        CreateNewClientButton.setBackground(new java.awt.Color(168, 199, 200));
        CreateNewClientButton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        CreateNewClientButton.setText("Create new client");
        CreateNewClientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateNewClientButtonActionPerformed(evt);
            }
        });

        CreateNewAccountButton.setBackground(new java.awt.Color(168, 199, 200));
        CreateNewAccountButton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        CreateNewAccountButton.setText("Create new banking account");
        CreateNewAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateNewAccountButtonActionPerformed(evt);
            }
        });

        DeleteBankingAccount.setBackground(new java.awt.Color(168, 199, 200));
        DeleteBankingAccount.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        DeleteBankingAccount.setText("Delete banking account");
        DeleteBankingAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBankingAccountActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(168, 199, 200));
        jButton5.setText("jButton5");

        javax.swing.GroupLayout ManagementPanelLayout = new javax.swing.GroupLayout(ManagementPanel);
        ManagementPanel.setLayout(ManagementPanelLayout);
        ManagementPanelLayout.setHorizontalGroup(
            ManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ManagementPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DeleteBankingAccount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CreateNewAccountButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CreateNewClientButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36))
        );
        ManagementPanelLayout.setVerticalGroup(
            ManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManagementPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(CreateNewClientButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CreateNewAccountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DeleteBankingAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(181, Short.MAX_VALUE))
        );

        MenuCardLayoutPanel.add(ManagementPanel, "card2");

        getContentPane().add(MenuCardLayoutPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 260, 450));

        CentralCardLayoutPanel.setMaximumSize(new java.awt.Dimension(804, 680));
        CentralCardLayoutPanel.setMinimumSize(new java.awt.Dimension(804, 680));
        CentralCardLayoutPanel.setOpaque(false);
        CentralCardLayoutPanel.setPreferredSize(new java.awt.Dimension(804, 680));
        CentralCardLayoutPanel.setLayout(new java.awt.CardLayout());

        WelcomePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Welcome_lbl.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        Welcome_lbl.setForeground(new java.awt.Color(0, 153, 153));
        Welcome_lbl.setText("Welcome to the Administration Management System ");
        WelcomePanel.add(Welcome_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, 80));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/partAbstrBackgr.jpg"))); // NOI18N
        WelcomePanel.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 613));

        CentralCardLayoutPanel.add(WelcomePanel, "card5");

        RegistrationPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registration", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 2, 24), new java.awt.Color(0, 153, 153))); // NOI18N
        RegistrationPanel.setForeground(new java.awt.Color(0, 153, 153));
        RegistrationPanel.setMaximumSize(new java.awt.Dimension(804, 680));
        RegistrationPanel.setMinimumSize(new java.awt.Dimension(804, 680));
        RegistrationPanel.setOpaque(false);
        RegistrationPanel.setPreferredSize(new java.awt.Dimension(804, 680));
        RegistrationPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("First name");
        RegistrationPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, -1));

        jLabel3.setText("Middle name");
        RegistrationPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 128, -1, -1));

        jLabel4.setText("Last name");
        RegistrationPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 166, -1, -1));

        jLabel5.setText("Personal Id Number ");
        RegistrationPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        jLabel6.setText("Address:  district./.........Str./........№/....fl./....ap./.... ");
        RegistrationPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, -1, -1));
        RegistrationPanel.add(Nme_registr, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 122, -1));
        RegistrationPanel.add(secondName_resitr, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 156, -1));
        RegistrationPanel.add(surNme_registr, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 156, -1));
        RegistrationPanel.add(PIN_registr, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 125, -1));
        RegistrationPanel.add(address_registr, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 437, -1));

        jLabel7.setText("Country");
        RegistrationPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, -1, -1));

        comboBoxCountry.setBackground(new java.awt.Color(160, 199, 200));
        comboBoxCountry.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Изберете държава", "Австралия", "Австрия", "Азербайджан", "Албания", "Алжир", "Ангола", "Андора", "Аржентина", "Армения", "Афганистан", "Бангладеш", "Барбадос", "Бахамски острови", "Бахрейн", "Беларус", "Белгия", "Боливия", "Босна и Херцеговина", "Бразилия", "Бруней", "България", "Венецуела", "Виетнам", "Габон", "Гамбия", "Гана", "Гватемала", "Гвинея", "Гърция", "Дания", "Египет", "Еквадор", "Израел", "Ирак", "Иран", "Ирландия", "Исландия", "Испания", "Италия", "Канада", "Катар", "Кения", "Кипър", "Куба", " " }));
        RegistrationPanel.add(comboBoxCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 145, -1));

        jLabel8.setText("City");
        RegistrationPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 27, -1));
        RegistrationPanel.add(city_registr, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 113, -1));

        jLabel9.setText("Telephone number");
        RegistrationPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, -1, -1));

        jLabel10.setText("E-mail ");
        RegistrationPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, -1, -1));
        RegistrationPanel.add(phone_restr, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, 116, -1));
        RegistrationPanel.add(mail_registr, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 440, 200, -1));

        ConfirmButton.setBackground(new java.awt.Color(168, 199, 200));
        ConfirmButton.setText("Confirm");
        ConfirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmButtonActionPerformed(evt);
            }
        });
        RegistrationPanel.add(ConfirmButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 503, 70, 30));

        jLabel1.setText("Username");
        RegistrationPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 52, -1, -1));
        RegistrationPanel.add(userName_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 122, -1));

        jLabel17.setText("Acess level");
        RegistrationPanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 470, -1, -1));

        CancelButton.setBackground(new java.awt.Color(168, 199, 200));
        CancelButton.setText("Cancel");
        RegistrationPanel.add(CancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 503, 73, 30));

        jLabel20.setText("Date of birth");
        RegistrationPanel.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, -1, -1));

        comboBoxDateOfBirth.setBackground(new java.awt.Color(168, 199, 200));
        comboBoxDateOfBirth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "[Date]", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", " " }));
        comboBoxDateOfBirth.setMaximumSize(new java.awt.Dimension(61, 20));
        RegistrationPanel.add(comboBoxDateOfBirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 70, -1));

        comboBoxMonthOfBirth.setBackground(new java.awt.Color(168, 199, 200));
        comboBoxMonthOfBirth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "[Month]", "Jan", "Feb", "March", "April", "May", "June", "July", "Aug", "Sep", "Oct", "Nov", "Dec" }));
        comboBoxMonthOfBirth.setMaximumSize(new java.awt.Dimension(61, 20));
        RegistrationPanel.add(comboBoxMonthOfBirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 70, -1));

        comboBoxYearOfBirth.setBackground(new java.awt.Color(168, 199, 200));
        comboBoxYearOfBirth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "[Year]", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", " ", " " }));
        comboBoxYearOfBirth.setMaximumSize(new java.awt.Dimension(61, 20));
        RegistrationPanel.add(comboBoxYearOfBirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 70, -1));

        comboBoxUserType.setBackground(new java.awt.Color(160, 199, 200));
        comboBoxUserType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Изберете тип на потребителя", "Банков служител", "Депозиращ Клиент", "Клиент" }));
        RegistrationPanel.add(comboBoxUserType, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 470, 190, -1));

        CentralCardLayoutPanel.add(RegistrationPanel, "RegistrationCard");
        RegistrationPanel.getAccessibleContext().setAccessibleParent(CentralCardLayoutPanel);

        NewAccountPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        NewAccountPanel.setMaximumSize(new java.awt.Dimension(804, 680));
        NewAccountPanel.setMinimumSize(new java.awt.Dimension(804, 680));
        NewAccountPanel.setPreferredSize(new java.awt.Dimension(804, 680));
        NewAccountPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setText("First name");
        NewAccountPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, -1));
        NewAccountPanel.add(fnme_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 130, -1));

        jLabel12.setText("Middlename");
        NewAccountPanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, -1));
        NewAccountPanel.add(mname_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 150, -1));

        jLabel13.setText("Last name");
        NewAccountPanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, 20));
        NewAccountPanel.add(lname_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 150, -1));

        jLabel14.setText("Personal Id Number");
        NewAccountPanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));
        NewAccountPanel.add(egn_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 130, -1));

        jLabel15.setText("Username");
        NewAccountPanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));
        NewAccountPanel.add(user_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 130, -1));

        jComboBox2.setBackground(new java.awt.Color(160, 199, 200));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select type ", "-----------------------------", "Regular Savings", "Standard deposit ", "Fixed deposit", "Noticed deposit", " " }));
        NewAccountPanel.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 180, -1));

        jLabel16.setText("Account type");
        NewAccountPanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, -1, -1));

        jLabel18.setText("Acess level");
        NewAccountPanel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));
        NewAccountPanel.add(access_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 70, -1));

        search_button.setText("Search");
        search_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_buttonActionPerformed(evt);
            }
        });
        NewAccountPanel.add(search_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, -1, -1));

        PartBackground_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/partAbstrBackgr.jpg"))); // NOI18N
        PartBackground_lbl.setText("Фамилия");
        PartBackground_lbl.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PartBackground_lbl.setMaximumSize(new java.awt.Dimension(804, 700));
        PartBackground_lbl.setMinimumSize(new java.awt.Dimension(804, 700));
        PartBackground_lbl.setPreferredSize(new java.awt.Dimension(804, 680));
        NewAccountPanel.add(PartBackground_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 725, 606));

        CentralCardLayoutPanel.add(NewAccountPanel, "createAccountCard");

        BackgroundPart_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/partAbstrBackgr.jpg"))); // NOI18N
        BackgroundPart_lbl.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout DeleteAccountPanelLayout = new javax.swing.GroupLayout(DeleteAccountPanel);
        DeleteAccountPanel.setLayout(DeleteAccountPanelLayout);
        DeleteAccountPanelLayout.setHorizontalGroup(
            DeleteAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 724, Short.MAX_VALUE)
            .addGroup(DeleteAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(BackgroundPart_lbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DeleteAccountPanelLayout.setVerticalGroup(
            DeleteAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 666, Short.MAX_VALUE)
            .addGroup(DeleteAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(BackgroundPart_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        CentralCardLayoutPanel.add(DeleteAccountPanel, "DeleteAcntCard");

        getContentPane().add(CentralCardLayoutPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 610, 590));

        BackgroundLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/abstract_background.jpg"))); // NOI18N
        getContentPane().add(BackgroundLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -5, -1, 1190));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DeleteBankingAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBankingAccountActionPerformed
        CardLayout deleteAccount = (CardLayout) (CentralCardLayoutPanel.getLayout());
        deleteAccount.show(CentralCardLayoutPanel, "DeleteAcntCard");        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteBankingAccountActionPerformed

    private void CreateNewClientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateNewClientButtonActionPerformed
        CardLayout registrationPanel = (CardLayout) (CentralCardLayoutPanel.getLayout());
        registrationPanel.show(CentralCardLayoutPanel, "RegistrationCard");
    }//GEN-LAST:event_CreateNewClientButtonActionPerformed

    private void CreateNewAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateNewAccountButtonActionPerformed

        CardLayout accoutPanel = (CardLayout) (CentralCardLayoutPanel.getLayout());
        

        accoutPanel.show(CentralCardLayoutPanel, "createAccountCard");
    }//GEN-LAST:event_CreateNewAccountButtonActionPerformed

    private void ConfirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmButtonActionPerformed

        String user = userName_txt.getText();
        String pass = "elu" + PIN_registr.getText();
        String Fname = Nme_registr.getText();
        String Mname = secondName_resitr.getText();
        String Lname = surNme_registr.getText();
        String pin = PIN_registr.getText();
        String bday = (String) comboBoxDateOfBirth.getSelectedItem();
        String bmonth = (String) comboBoxMonthOfBirth.getSelectedItem();
        String byear = (String) comboBoxYearOfBirth.getSelectedItem();
        String country = (String) comboBoxCountry.getSelectedItem();
        String city = city_registr.getText();
        String address = address_registr.getText();
        String phone = phone_restr.getText();
        String email = mail_registr.getText();
        String access = comboBoxUserType.getSelectedIndex() + "";
        String request = "create";

        
        
        // check eng field for 10 digits
        Pattern egn_val = Pattern.compile("\\d{10,10}");
        Matcher m_val = egn_val.matcher(pin);
        if (!m_val.find()) {
            JOptionPane.showMessageDialog(null, "EGN може да съдържа само цифри");
            return;
        }
        
        if (user.trim().length() == 0 || Fname.length() == 0 || Mname.trim().length() == 0
                || Lname.trim().length() == 0 || pin.trim().length() == 0
                || country.trim().length() == 0 || city.trim().length() == 0
                || address.length() == 0 || phone.length() == 0 || email.length() == 0
                || comboBoxCountry.getSelectedIndex() == 0 || comboBoxDateOfBirth.getSelectedIndex() == 0
                || comboBoxMonthOfBirth.getSelectedIndex() == 0 || comboBoxYearOfBirth.getSelectedIndex() == 0
                || comboBoxUserType.getSelectedIndex() == 0) {

            JOptionPane.showMessageDialog(null, "Please fill all the fields!");
            return;
        }
        
        
        

        SSLClient client = new SSLClient();

        newUser = new User(user, pass, Fname, Mname, Lname, pin, bday, bmonth, byear,
                country, city, address, phone, email, access);
        newUser.setRequest(request);
        newUser = (User) client.runClient(newUser);
        
        if (newUser.getResponse() == null) {
            clearRegistrationForm();
            JOptionPane.showMessageDialog(null, "New User Successfully Created!");
            return;
        }

        if (newUser.getResponse().equalsIgnoreCase("userExists")) {
            JOptionPane.showMessageDialog(null, "Username already exists!");
            return;
        }

        if (newUser.getResponse().equalsIgnoreCase("egnExists")) {
            JOptionPane.showMessageDialog(null, "PIN number already exists!");
            return;
        }
    }//GEN-LAST:event_ConfirmButtonActionPerformed

    private void search_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_buttonActionPerformed
        
      
      
        String pin = egn_txt.getText();
        String request = "create";
        
        Pattern egn_val = Pattern.compile("\\d{10,10}");
        Matcher m_val = egn_val.matcher(pin);
        if (!m_val.find()) {
            JOptionPane.showMessageDialog(null, "EGN може да съдържа само цифри");
            return;
        }
        
          
          
         SSLClient client = new SSLClient();
         
 // TUK TRQBVA NOV REQUEST ZA SMETKA i NOV User
         
     //   newUser = new User(user, Fname, Mname, Lname, pin, access);
        newUser.setRequest(request);
        newUser = (User) client.runClient(newUser);
        
        
        if (newUser.getResponse() == null) {
            clearRegistrationForm();
            JOptionPane.showMessageDialog(null, "New User Successfully Created!");
            return;
        }
        
        
        
    }//GEN-LAST:event_search_buttonActionPerformed

     public void setUser(User user) {
        this.currentUser = user;
    }

    public void loadUserInfo() {
        String name = currentUser.getName();
        String familyname = currentUser.getFamilyname();
        String surname = currentUser.getSurname();
        fnme_txt.setText(name);
        mname_txt.setText(surname);
        lname_txt.setText(familyname);
        user_txt.setText(currentUser.getUsername());
        access_txt.setText(currentUser.getUserType());
    }

    private User currentUser = new User();
    private void clearRegistrationForm() {
        userName_txt.setText("");
        Nme_registr.setText("");
        secondName_resitr.setText("");
        surNme_registr.setText("");
        PIN_registr.setText("");
        comboBoxDateOfBirth.setSelectedIndex(0);
        comboBoxMonthOfBirth.setSelectedIndex(0);
        comboBoxYearOfBirth.setSelectedIndex(0);
        comboBoxCountry.setSelectedIndex(0);
        city_registr.setText("");
        address_registr.setText("");
        phone_restr.setText("");
        mail_registr.setText("");
        comboBoxUserType.setSelectedIndex(0);
    }

    private User newUser;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundLbl;
    private javax.swing.JLabel BackgroundPart_lbl;
    private javax.swing.JButton CancelButton;
    private javax.swing.JPanel CentralCardLayoutPanel;
    private javax.swing.JButton ConfirmButton;
    private javax.swing.JButton CreateNewAccountButton;
    private javax.swing.JButton CreateNewClientButton;
    private javax.swing.JPanel DeleteAccountPanel;
    private javax.swing.JButton DeleteBankingAccount;
    private javax.swing.JLabel ELUBank_lbl;
    private javax.swing.JPanel ManagementPanel;
    private javax.swing.JPanel MenuCardLayoutPanel;
    private javax.swing.JPanel NewAccountPanel;
    private javax.swing.JTextField Nme_registr;
    private javax.swing.JTextField PIN_registr;
    private javax.swing.JLabel PartBackground_lbl;
    private javax.swing.JPanel RegistrationPanel;
    private javax.swing.JPanel WelcomePanel;
    private javax.swing.JLabel Welcome_lbl;
    private javax.swing.JTextField access_txt;
    private javax.swing.JTextField address_registr;
    private javax.swing.JTextField city_registr;
    private javax.swing.JComboBox comboBoxCountry;
    private javax.swing.JComboBox comboBoxDateOfBirth;
    private javax.swing.JComboBox comboBoxMonthOfBirth;
    private javax.swing.JComboBox comboBoxUserType;
    private javax.swing.JComboBox comboBoxYearOfBirth;
    private javax.swing.JTextField egn_txt;
    private javax.swing.JTextField fnme_txt;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lname_txt;
    private javax.swing.JTextField mail_registr;
    private javax.swing.JTextField mname_txt;
    private javax.swing.JTextField phone_restr;
    private javax.swing.JButton search_button;
    private javax.swing.JTextField secondName_resitr;
    private javax.swing.JTextField surNme_registr;
    private javax.swing.JTextField userName_txt;
    private javax.swing.JTextField user_txt;
    // End of variables declaration//GEN-END:variables
}
