
import java.awt.Component;
import java.beans.PropertyChangeEvent;
import javax.swing.JTextField;

/**
 *
 * @author Elena Koevska
 */
public class UserProfilePanel extends ClientFramePanel {

    /**
     * Creates new UserProfilePanel form.
     */
    public UserProfilePanel() {
        initComponents();
    }

    /**
     * Updates component state when main frame fires a property change event.
     *
     * @param pce PropertyChangeEvent instance.
     * @see ClientFramePanel#propertyChange
     */
    @Override
    public void propertyChange(PropertyChangeEvent pce) {
        // Call parent class implementation.
        super.propertyChange(pce);
        
        updateUIState();
    }

    /**
     * Updates UI elements values.
     */
    private void updateUIState() {
        fieldMail.setText(user.getEmail());
        fieldPhone.setText(user.getPhone());
        fieldAddress.setText(user.getAddress());
        fieldCity.setText(user.getCity());
        comboCountry.setSelectedItem(user.getCountry());
    }

    /**
     * Updates user profile information on server-side.
     */
    private void updateUserInfo() {
        // Basic validation - ensure that the fields are not empty.
        for (Component c : getComponents()) {
            if (c instanceof JTextField) {
                if (((JTextField) c).getText().isEmpty()) {
                    showErrMsg("Полетата не може да са празни!");
                    return;
                }
            }
        }

        // Make new request object.
        User request = new User();

        // Fill it with the new information from the UI elements.
        request.setEmail(fieldMail.getText());
        request.setPhone(fieldPhone.getText());
        request.setAddress(fieldAddress.getText());
        request.setCity(fieldCity.getText());
        request.setCountry((String) comboCountry.getSelectedItem());

        // Add user PIN so it can be identified server-side.
        request.setEgn(user.getEgn());

        // Set request type.
        request.setRequest("update");

        // Make the request and get the response.
        User response = (User) main.getSSLClient().runClient(request);

        if (response.getResponse() == null) {
            // Operation was successful.
            // Update current user instance with the new information.
            user.setEmail(response.getEmail());
            user.setPhone(response.getPhone());
            user.setAddress(response.getAddress());
            user.setCity(response.getCity());
            user.setCountry(response.getCountry());

            showInfoMsg("Промените са запазени успешно.");
        } else {
            // Some error occurred in the server application.
            // Revert UI elements to the old values.
            updateUIState();

            showErrMsg("Грешка при запазване на промените: " + response.getResponse());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMail = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        lblCountry = new javax.swing.JLabel();
        fieldMail = new javax.swing.JTextField();
        fieldPhone = new javax.swing.JTextField();
        fieldAddress = new javax.swing.JTextField();
        fieldCity = new javax.swing.JTextField();
        comboCountry = new javax.swing.JComboBox();
        btnSaveChanges = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Моят профил", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 16), new java.awt.Color(120, 169, 203))); // NOI18N
        setMaximumSize(new java.awt.Dimension(804, 688));
        setMinimumSize(new java.awt.Dimension(804, 688));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(804, 688));

        lblMail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMail.setText("E-mail");

        lblPhone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPhone.setText("Телефон");

        lblAddress.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblAddress.setText("Адрес");

        lblCity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCity.setText("Град");

        lblCountry.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCountry.setText("Държава");

        fieldMail.setMaximumSize(new java.awt.Dimension(350, 24));
        fieldMail.setMinimumSize(new java.awt.Dimension(350, 24));
        fieldMail.setPreferredSize(new java.awt.Dimension(350, 24));

        fieldPhone.setMaximumSize(new java.awt.Dimension(350, 24));
        fieldPhone.setMinimumSize(new java.awt.Dimension(350, 24));
        fieldPhone.setPreferredSize(new java.awt.Dimension(350, 24));

        fieldAddress.setMaximumSize(new java.awt.Dimension(350, 24));
        fieldAddress.setMinimumSize(new java.awt.Dimension(350, 24));
        fieldAddress.setPreferredSize(new java.awt.Dimension(350, 24));

        fieldCity.setMaximumSize(new java.awt.Dimension(350, 24));
        fieldCity.setMinimumSize(new java.awt.Dimension(350, 24));
        fieldCity.setPreferredSize(new java.awt.Dimension(350, 24));

        comboCountry.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Австралия", "Австрия", "Азербайджан", "Албания", "Алжир", "Американска Самоа", "Англия", "Ангола", "Андора", "Антигуа и Барбуда", "Аржентина", "Армения", "Афганистан", "Бангладеш", "Барбадос", "Бахамски острови", "Бахрейн", "Беларус", "Белгия", "Белиз", "Бенин", "Боливия", "Босна и Херцеговина", "Ботсвана", "Бразилия", "Бруней", "Буркина Фасо", "Бурунди", "Бутан", "България", "Вануату", "Ватикан", "Венецуела", "Виетнам", "Габон", "Гамбия", "Гана", "Гватемала", "Гвиана", "Гвинея", "Гвинея-Бисау", "Германия", "Гренада", "Гренландия", "Грузия", "Гуам", "Гърция", "Дания", "Демократична република Конго", "Джибути", "Доминиканска република", "Доминика", "Египет", "Еквадор", "Екваториална Гвинея", "Еритрея", "Естония", "Етиопия", "Замбия", "Западна Сахара", "Зимбабве", "Израел", "Източен Тимор", "Индия", "Индонезия", "Ирак", "Иран", "Ирландия", "Исландия", "Испания", "Италия", "Йемен", "Йордания", "Кабо Верде", "Казахстан", "Камбоджа", "Камерун", "Канада", "Катар", "Кения", "Кипър", "Киргизстан", "Кирибати", "Китай", "Колумбия", "Коморски острови", "Конго", "Коста Рика", "Кот д'Ивоар", "Куба", "Кувейт", "Лаос", "Латвия", "Лесото", "Либерия", "Либия", "Лисабон", "Литва", "Лихтенщайн", "Люксембург", "Мавритания", "Мавриций", "Мадагаскар", "Македония", "Малави", "Малайзия", "Малдиви", "Мали", "Малта", "Мариански острови", "Мароко", "Маршалови острови", "Мексико", "Мианмар", "Микронезия", "Мозамбик", "Молдова", "Монако", "Монголия", "Намибия", "Непал", "Нигерия", "Нигер", "Никарагуа", "Ниуе", "Нова Зеландия", "Нова Каледония", "Норвегия", "ОАЕ", "Оман", "Острови Кук", "Пакистан", "Палау", "Панама", "Папуа - Нова Гвинея", "Парагвай", "Перу", "Питкерн", "Полша", "Португалия", "Руанда", "Румъния", "Русия", "Русия", "САЩ", "Салвадор", "Самоа", "Сан Марино", "Саудитска Арабия", "Свазиленд", "Северна Корея", "Сейнт Винсент и Гренадини", "Сейнт Китс и Невис", "Сейнт Лусия", "Сейшелски острови", "Сенегал", "Сиера Леоне", "Сингапур", "Сирия", "Словакия", "Словения", "Соломонови острови", "Сомалия", "Судан", "Суринам", "Сърбия", "Таджикистан", "Тайван", "Тайланд", "Танзания", "Тибет", "Того", "Тонга", "Тринидад и Тобаго", "Тувалу", "Тунис", "Туркменистан", "Турция", "Турция", "Уганда", "Узбекистан", "Украйна", "Унгария", "Уругвай", "Фиджи", "Филипини", "Финландия", "Франция", "Френска Полинезия", "Хаити", "Холандия", "Хондурас", "Хърватия", "ЦАР", "Чад", "Черна гора", "Чехия", "Чили", "Швейцария", "Швеция", "Шри Ланка", "ЮАР", "Южна Корея", "Ямайка", "Япония" }));
        comboCountry.setMaximumSize(new java.awt.Dimension(350, 24));
        comboCountry.setMinimumSize(new java.awt.Dimension(350, 24));
        comboCountry.setPreferredSize(new java.awt.Dimension(350, 24));

        btnSaveChanges.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSaveChanges.setText("Запази промените");
        btnSaveChanges.setMaximumSize(new java.awt.Dimension(151, 32));
        btnSaveChanges.setMinimumSize(new java.awt.Dimension(151, 32));
        btnSaveChanges.setPreferredSize(new java.awt.Dimension(151, 32));
        btnSaveChanges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveChangesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSaveChanges, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCity)
                            .addComponent(lblAddress)
                            .addComponent(lblCountry)
                            .addComponent(lblPhone)
                            .addComponent(lblMail))
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(fieldMail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fieldPhone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fieldCity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fieldAddress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(comboCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(262, 262, 262))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(fieldMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMail))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(fieldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPhone))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(fieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddress))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(fieldCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCity))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblCountry)
                    .addComponent(comboCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(btnSaveChanges, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(363, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Save changes button event handler.
     *
     * @param evt ActionEvent instance.
     */
    private void btnSaveChangesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveChangesActionPerformed
        updateUserInfo();
    }//GEN-LAST:event_btnSaveChangesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSaveChanges;
    private javax.swing.JComboBox comboCountry;
    private javax.swing.JTextField fieldAddress;
    private javax.swing.JTextField fieldCity;
    private javax.swing.JTextField fieldMail;
    private javax.swing.JTextField fieldPhone;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCountry;
    private javax.swing.JLabel lblMail;
    private javax.swing.JLabel lblPhone;
    // End of variables declaration//GEN-END:variables
}
